### ISSUE TITLE
:( i think ur app crashed

### ISSUE THREAD

**Issue by limsiying** [AY1920S1-CS2113T-W12-4/main#159]
[What happened](https://github.com/limsiying/ped/issues/1):

- Null pointer exception thrown when show/previous is entered upon launch.
- Null pointer exception thrown when show/previous for non-existing commands are entered (eg entered only 2 commands but show 4).

After the second null pointer the app crashed oof so I exited and tried to enter again but then it started to throw run time exception.

![ur app crashed](https://user-images.githubusercontent.com/42372947/68016335-540bcc80-fccf-11e9-96be-2eae34df9ff8.PNG)
![what i entered](https://user-images.githubusercontent.com/42372947/68016342-55d59000-fccf-11e9-9dac-fb76154cf878.PNG)
![what is this](https://user-images.githubusercontent.com/42372947/68016598-da281300-fccf-11e9-9424-f815e4c6473d.PNG)

Hope I wasn't using it wrong :')

**Comment by 0325961** [comment]
The bug have been resolved. Thank you.
